import { i18n } from '@lingui/core'

export async function loadCatalog(locale: string) {
  // Vite requires static part of dynamic import to include file extension
  let messages: Record<string, string>
  switch (locale) {
    case 'en':
      // @ts-expect-error - messages.js is generated by lingui
      messages = (await import('./locales/en/messages.js')).default
      break
    case 'vi':
      // @ts-expect-error - messages.js is generated by lingui
      messages = (await import('./locales/vi/messages.js')).default
      break
    default:
      // @ts-expect-error - messages.js is generated by lingui
      messages = (await import('./locales/en/messages.js')).default
      break
  }
  return messages
}

export async function activateLocale(locale: string) {
  const messages = await loadCatalog(locale)
  i18n.load(locale, messages)
  i18n.activate(locale)
}


