import './global.css';
import { I18nProvider } from '../components/I18nProvider';

export const metadata = {
  title: 'Welcome to auth',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <I18nProvider locale="en">
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
